spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${services.keycloak-service}/realms/webber
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 5566